// Type definitions for bval 0.1.0
// Project: https://github.com/bcoin-org/bsock
// Definitions by: Joe Miyamoto <joemphilips@gmail.com>

/** Declaration file generated by dts-gen */

declare module 'bval' {
  import { Request } from 'bweb';
  export class Validator {
    public map: Map<string | number, any>;
    constructor(map: Map<string | number, any>, loose?: boolean);
    static fromRequest(req: Request): Validator;
    [key: string]: any;
  }
}
